/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

// biome-ignore lint/suspicious/noExplicitAny: Auto-generated registry index with dynamic component types
export const Index: Record<string, any> = {
  "chart": {
    name: "chart",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/chart.tsx",
      type: "registry:component",
      target: "components/nqchart/ui/chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/tooltip.tsx",
      type: "registry:component",
      target: "components/nqchart/ui/tooltip.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/tooltip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "tooltip"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "legend": {
    name: "legend",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/legend.tsx",
      type: "registry:component",
      target: "components/nqchart/ui/legend.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/legend.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "legend"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dot": {
    name: "dot",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/dot.tsx",
      type: "registry:component",
      target: "components/nqchart/ui/dot.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/dot.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "dot"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "nq-brush": {
    name: "nq-brush",
    description: "",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart"],
    files: [{
      path: "@/registry/ui/nq-brush.tsx",
      type: "registry:component",
      target: "components/nqchart/ui/nq-brush.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/nq-brush.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "nq-brush"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "background": {
    name: "background",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/background.tsx",
      type: "registry:component",
      target: "components/nqchart/ui/background.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/background.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "background"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart": {
    name: "bar-chart",
    description: "Bar chart (ECharts engine, compound API)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/bar-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "line-chart": {
    name: "line-chart",
    description: "Line chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/line-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/line-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "composed-chart": {
    name: "composed-chart",
    description: "Composed bar + line chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/composed-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/composed-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "composed-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pie-chart": {
    name: "pie-chart",
    description: "Pie / donut chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/pie-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/pie-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "pie-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "heatmap-chart": {
    name: "heatmap-chart",
    description: "Heatmap chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/heatmap-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/heatmap-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/heatmap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "heatmap-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "calendar-chart": {
    name: "calendar-chart",
    description: "Calendar heatmap chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/calendar-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/calendar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/calendar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "calendar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radial-chart": {
    name: "radial-chart",
    description: "Radial / gauge chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/radial-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/radial-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "radial-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart": {
    name: "area-chart",
    description: "Area chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/area-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/area-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "area-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scatter-chart": {
    name: "scatter-chart",
    description: "Scatter / bubble chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/scatter-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/scatter-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/scatter-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "scatter-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radar-chart": {
    name: "radar-chart",
    description: "Radar chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/radar-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/radar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "radar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart": {
    name: "funnel-chart",
    description: "Funnel chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/funnel-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/funnel-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/funnel-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "funnel-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waterfall-chart": {
    name: "waterfall-chart",
    description: "Waterfall chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/waterfall-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/waterfall-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/waterfall-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "waterfall-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "treemap-chart": {
    name: "treemap-chart",
    description: "Treemap chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/treemap-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/treemap-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/treemap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "treemap-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sparkline-chart": {
    name: "sparkline-chart",
    description: "Sparkline chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@nqchart/chart","@nqchart/tooltip","@nqchart/legend"],
    files: [{
      path: "@/registry/charts/sparkline-chart.tsx",
      type: "registry:component",
      target: "components/nqchart/charts/sparkline-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/sparkline-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "sparkline-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chart-recipes": {
    name: "chart-recipes",
    description: "Data helpers for histogram, Pareto, heatmap, bullet, gauge, and box plot shapes",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/lib/chart-recipes.ts",
      type: "registry:lib",
      target: "lib/chart-recipes.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/chart-recipes.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "chart-recipes"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bar-chart": {
    name: "ex-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-bar-chart": {
    name: "ex-loading-state-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-loading-state-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stacked-type-bar-chart": {
    name: "ex-stacked-type-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-stacked-type-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-stacked-type-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-stacked-type-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-percent-type-bar-chart": {
    name: "ex-percent-type-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-percent-type-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-percent-type-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-percent-type-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-horizontal-layout-bar-chart": {
    name: "ex-horizontal-layout-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-horizontal-layout-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-horizontal-layout-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-horizontal-layout-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hatched-variant-bar-chart": {
    name: "ex-hatched-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-hatched-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-hatched-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-hatched-variant-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stripped-variant-bar-chart": {
    name: "ex-stripped-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-stripped-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-stripped-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-stripped-variant-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-line-chart": {
    name: "ex-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-line-chart": {
    name: "ex-loading-state-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-loading-state-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-composed-chart": {
    name: "ex-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/composed-chart"],
    files: [{
      path: "@/registry/examples/ex-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-composed-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-composed-chart": {
    name: "ex-loading-state-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/composed-chart"],
    files: [{
      path: "@/registry/examples/ex-loading-state-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-composed-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-pareto-chart": {
    name: "ex-pareto-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/composed-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-pareto-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-pareto-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-pareto-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-pie-chart": {
    name: "ex-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/pie-chart"],
    files: [{
      path: "@/registry/examples/ex-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-pie-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gauge-chart": {
    name: "ex-gauge-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-gauge-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-gauge-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-gauge-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gauge-with-target-chart": {
    name: "ex-gauge-with-target-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-gauge-with-target-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-gauge-with-target-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-gauge-with-target-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-histogram-chart": {
    name: "ex-histogram-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-histogram-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-histogram-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-histogram-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-histogram-chart": {
    name: "ex-loading-state-histogram-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-loading-state-histogram-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-histogram-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-histogram-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bullet-chart": {
    name: "ex-bullet-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-bullet-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-bullet-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-bullet-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-pareto-chart": {
    name: "ex-loading-state-pareto-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/composed-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-loading-state-pareto-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-pareto-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-pareto-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-boxplot-chart": {
    name: "ex-boxplot-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/composed-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-boxplot-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-boxplot-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-boxplot-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-chart": {
    name: "ex-heatmap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/heatmap-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-weekly-chart": {
    name: "ex-heatmap-weekly-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/heatmap-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-weekly-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-weekly-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-weekly-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-correlation-chart": {
    name: "ex-heatmap-correlation-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/heatmap-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-correlation-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-correlation-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-correlation-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-workload-dashboard-chart": {
    name: "ex-workload-dashboard-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/calendar-chart","@nqchart/heatmap-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-workload-dashboard-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-workload-dashboard-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-workload-dashboard-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-calendar-workload-chart": {
    name: "ex-calendar-workload-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/calendar-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-calendar-workload-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-calendar-workload-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-calendar-workload-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-team-workload-chart": {
    name: "ex-heatmap-team-workload-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/heatmap-chart","@nqchart/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-team-workload-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-team-workload-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-team-workload-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-dots-line-chart": {
    name: "ex-bg-dots-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgDotsLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgDotsLineChart"},
  },
  "ex-bg-graph-paper-line-chart": {
    name: "ex-bg-graph-paper-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgGraphPaperLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgGraphPaperLineChart"},
  },
  "ex-bg-cross-hatch-line-chart": {
    name: "ex-bg-cross-hatch-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgCrossHatchLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgCrossHatchLineChart"},
  },
  "ex-bg-diagonal-lines-line-chart": {
    name: "ex-bg-diagonal-lines-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgDiagonalLinesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgDiagonalLinesLineChart"},
  },
  "ex-bg-plus-line-chart": {
    name: "ex-bg-plus-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgPlusLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgPlusLineChart"},
  },
  "ex-bg-falling-triangles-line-chart": {
    name: "ex-bg-falling-triangles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgFallingTrianglesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgFallingTrianglesLineChart"},
  },
  "ex-bg-4-pointed-star-line-chart": {
    name: "ex-bg-4-pointed-star-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBg4PointedStarLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBg4PointedStarLineChart"},
  },
  "ex-bg-tiny-checkers-line-chart": {
    name: "ex-bg-tiny-checkers-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgTinyCheckersLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgTinyCheckersLineChart"},
  },
  "ex-bg-overlapping-circles-line-chart": {
    name: "ex-bg-overlapping-circles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgOverlappingCirclesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgOverlappingCirclesLineChart"},
  },
  "ex-bg-wiggle-lines-line-chart": {
    name: "ex-bg-wiggle-lines-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgWiggleLinesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgWiggleLinesLineChart"},
  },
  "ex-bg-bubbles-line-chart": {
    name: "ex-bg-bubbles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleBgBubblesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgBubblesLineChart"},
  },
  "ex-legend-square-line-chart": {
    name: "ex-legend-square-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendSquareLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendSquareLineChart"},
  },
  "ex-legend-circle-line-chart": {
    name: "ex-legend-circle-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendCircleLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendCircleLineChart"},
  },
  "ex-legend-circle-outline-line-chart": {
    name: "ex-legend-circle-outline-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendCircleOutlineLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendCircleOutlineLineChart"},
  },
  "ex-legend-rounded-square-line-chart": {
    name: "ex-legend-rounded-square-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendRoundedSquareLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendRoundedSquareLineChart"},
  },
  "ex-legend-rounded-square-outline-line-chart": {
    name: "ex-legend-rounded-square-outline-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendRoundedSquareOutlineLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendRoundedSquareOutlineLineChart"},
  },
  "ex-legend-vertical-bar-line-chart": {
    name: "ex-legend-vertical-bar-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendVerticalBarLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendVerticalBarLineChart"},
  },
  "ex-legend-horizontal-bar-line-chart": {
    name: "ex-legend-horizontal-bar-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleLegendHorizontalBarLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLegendHorizontalBarLineChart"},
  },
  "ex-tooltip-default-bar-chart": {
    name: "ex-tooltip-default-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleTooltipDefaultBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleTooltipDefaultBarChart"},
  },
  "ex-tooltip-frosted-glass-bar-chart": {
    name: "ex-tooltip-frosted-glass-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["NQExampleTooltipFrostedGlassBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleTooltipFrostedGlassBarChart"},
  },
  "ex-animated-dashed-stroke-area-chart": {
    name: "ex-animated-dashed-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleAnimatedDashedStrokeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleAnimatedDashedStrokeAreaChart"},
  },
  "ex-area-chart": {
    name: "ex-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleAreaChart"},
  },
  "ex-bg-bubbles-sparkline-chart": {
    name: "ex-bg-bubbles-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleBgBubblesSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBgBubblesSparklineChart"},
  },
  "ex-bubble-chart": {
    name: "ex-bubble-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleBubbleChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBubbleChart"},
  },
  "ex-bubble-sized-chart": {
    name: "ex-bubble-sized-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleBubbleSizedChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBubbleSizedChart"},
  },
  "ex-bump-curve-type-area-chart": {
    name: "ex-bump-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleBumpCurveTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleBumpCurveTypeAreaChart"},
  },
  "ex-chart-config-default-bar-chart": {
    name: "ex-chart-config-default-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleChartConfigDefaultBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleChartConfigDefaultBarChart"},
  },
  "ex-chart-config-icons-bar-chart": {
    name: "ex-chart-config-icons-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleChartConfigIconsBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleChartConfigIconsBarChart"},
  },
  "ex-circle-grid-radar-chart": {
    name: "ex-circle-grid-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleCircleGridRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleCircleGridRadarChart"},
  },
  "ex-dashed-stroke-area-chart": {
    name: "ex-dashed-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleDashedStrokeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleDashedStrokeAreaChart"},
  },
  "ex-default-type-area-chart": {
    name: "ex-default-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleDefaultTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleDefaultTypeAreaChart"},
  },
  "ex-dotted-area-variant-area-chart": {
    name: "ex-dotted-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleDottedAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleDottedAreaVariantAreaChart"},
  },
  "ex-expanded-type-area-chart": {
    name: "ex-expanded-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleExpandedTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleExpandedTypeAreaChart"},
  },
  "ex-funnel-chart": {
    name: "ex-funnel-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/funnel-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleFunnelChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleFunnelChart"},
  },
  "ex-glowing-bubble-chart": {
    name: "ex-glowing-bubble-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingBubbleChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingBubbleChart"},
  },
  "ex-glowing-funnel-chart": {
    name: "ex-glowing-funnel-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/funnel-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingFunnelChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingFunnelChart"},
  },
  "ex-glowing-radar-chart": {
    name: "ex-glowing-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingRadarChart"},
  },
  "ex-glowing-radial-chart": {
    name: "ex-glowing-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingRadialChart"},
  },
  "ex-glowing-scatter-chart": {
    name: "ex-glowing-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingScatterChart"},
  },
  "ex-glowing-sparkline-chart": {
    name: "ex-glowing-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingSparklineChart"},
  },
  "ex-glowing-treemap-chart": {
    name: "ex-glowing-treemap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/treemap-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingTreemapChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingTreemapChart"},
  },
  "ex-glowing-waterfall-chart": {
    name: "ex-glowing-waterfall-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/waterfall-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGlowingWaterfallChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGlowingWaterfallChart"},
  },
  "ex-gradient-area-variant-area-chart": {
    name: "ex-gradient-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientAreaVariantAreaChart"},
  },
  "ex-gradient-colors-area-chart": {
    name: "ex-gradient-colors-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientColorsAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientColorsAreaChart"},
  },
  "ex-gradient-colors-bar-chart": {
    name: "ex-gradient-colors-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientColorsBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientColorsBarChart"},
  },
  "ex-gradient-colors-bump-area-chart": {
    name: "ex-gradient-colors-bump-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientColorsBumpAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientColorsBumpAreaChart"},
  },
  "ex-gradient-colors-radar-chart": {
    name: "ex-gradient-colors-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientColorsRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientColorsRadarChart"},
  },
  "ex-gradient-colors-radial-chart": {
    name: "ex-gradient-colors-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientColorsRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientColorsRadialChart"},
  },
  "ex-gradient-colors-scatter-chart": {
    name: "ex-gradient-colors-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientColorsScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientColorsScatterChart"},
  },
  "ex-gradient-reverse-area-variant-area-chart": {
    name: "ex-gradient-reverse-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleGradientReverseAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleGradientReverseAreaVariantAreaChart"},
  },
  "ex-hatched-area-variant-area-chart": {
    name: "ex-hatched-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleHatchedAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleHatchedAreaVariantAreaChart"},
  },
  "ex-lines-area-variant-area-chart": {
    name: "ex-lines-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLinesAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLinesAreaVariantAreaChart"},
  },
  "ex-lines-variant-radar-chart": {
    name: "ex-lines-variant-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLinesVariantRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLinesVariantRadarChart"},
  },
  "ex-loading-state-area-chart": {
    name: "ex-loading-state-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateAreaChart"},
  },
  "ex-loading-state-bubble-chart": {
    name: "ex-loading-state-bubble-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateBubbleChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateBubbleChart"},
  },
  "ex-loading-state-funnel-chart": {
    name: "ex-loading-state-funnel-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/funnel-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateFunnelChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateFunnelChart"},
  },
  "ex-loading-state-gauge-chart": {
    name: "ex-loading-state-gauge-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateGaugeChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateGaugeChart"},
  },
  "ex-loading-state-radar-chart": {
    name: "ex-loading-state-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateRadarChart"},
  },
  "ex-loading-state-radial-chart": {
    name: "ex-loading-state-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateRadialChart"},
  },
  "ex-loading-state-scatter-chart": {
    name: "ex-loading-state-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateScatterChart"},
  },
  "ex-loading-state-sparkline-chart": {
    name: "ex-loading-state-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateSparklineChart"},
  },
  "ex-loading-state-treemap-chart": {
    name: "ex-loading-state-treemap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/treemap-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateTreemapChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateTreemapChart"},
  },
  "ex-loading-state-waterfall-chart": {
    name: "ex-loading-state-waterfall-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/waterfall-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleLoadingStateWaterfallChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleLoadingStateWaterfallChart"},
  },
  "ex-monotoney-curve-type-area-chart": {
    name: "ex-monotoney-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleMonotoneyCurveTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleMonotoneyCurveTypeAreaChart"},
  },
  "ex-radar-chart": {
    name: "ex-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleRadarChart"},
  },
  "ex-radial-chart": {
    name: "ex-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleRadialChart"},
  },
  "ex-scatter-chart": {
    name: "ex-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleScatterChart"},
  },
  "ex-semi-variant-radial-chart": {
    name: "ex-semi-variant-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSemiVariantRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSemiVariantRadialChart"},
  },
  "ex-rose-radial-chart": {
    name: "ex-rose-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleRoseRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleRoseRadialChart"},
  },
  "ex-solid-area-variant-area-chart": {
    name: "ex-solid-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSolidAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSolidAreaVariantAreaChart"},
  },
  "ex-solid-stroke-area-chart": {
    name: "ex-solid-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSolidStrokeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSolidStrokeAreaChart"},
  },
  "ex-sparkline-area-chart": {
    name: "ex-sparkline-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSparklineAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSparklineAreaChart"},
  },
  "ex-sparkline-chart": {
    name: "ex-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSparklineChart"},
  },
  "ex-stacked-type-area-chart": {
    name: "ex-stacked-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleStackedTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleStackedTypeAreaChart"},
  },
  "ex-step-curve-type-area-chart": {
    name: "ex-step-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleStepCurveTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleStepCurveTypeAreaChart"},
  },
  "ex-treemap-chart": {
    name: "ex-treemap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/treemap-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleTreemapChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleTreemapChart"},
  },
  "ex-waterfall-chart": {
    name: "ex-waterfall-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/waterfall-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleWaterfallChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleWaterfallChart"},
  },
  "ex-sparkline-end-dot-chart": {
    name: "ex-sparkline-end-dot-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSparklineEndDotChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSparklineEndDotChart"},
  },
  "ex-sparkline-reference-band-chart": {
    name: "ex-sparkline-reference-band-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@nqchart/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["NQExampleSparklineReferenceBandChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"NQExampleSparklineReferenceBandChart"},
  },
  "monospace-bar-chart": {
    name: "monospace-bar-chart",
    description: "Terminal-style bar chart with monospace KPI chrome (ECharts)",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-monospace-bar-chart.tsx",
      type: "registry:block",
      target: "components/nqchart/blocks/monospace-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-monospace-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "monospace-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "hover-trace-bar-chart": {
    name: "hover-trace-bar-chart",
    description: "Bar chart with KPI header trace (ECharts)",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-hover-trace-bar-chart.tsx",
      type: "registry:block",
      target: "components/nqchart/blocks/hover-trace-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-hover-trace-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "hover-trace-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-bar-chart": {
    name: "grid-bar-chart",
    description: "Stacked ghost grid bar chart (ECharts)",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-grid-bar-chart.tsx",
      type: "registry:block",
      target: "components/nqchart/blocks/grid-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-grid-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "grid-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "isometric-bar-chart": {
    name: "isometric-bar-chart",
    description: "Rounded bar chart block (ECharts)",
    type: "registry:block",
    registryDependencies: ["@nqchart/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-isometric-bar-chart.tsx",
      type: "registry:block",
      target: "components/nqchart/blocks/isometric-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-isometric-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "isometric-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }