/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

// biome-ignore lint/suspicious/noExplicitAny: Auto-generated registry index with dynamic component types
export const Index: Record<string, any> = {
  "chart": {
    name: "chart",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/chart.tsx",
      type: "registry:component",
      target: "components/beecharts/ui/chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/tooltip.tsx",
      type: "registry:component",
      target: "components/beecharts/ui/tooltip.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/tooltip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "tooltip"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "legend": {
    name: "legend",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/legend.tsx",
      type: "registry:component",
      target: "components/beecharts/ui/legend.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/legend.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "legend"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dot": {
    name: "dot",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/dot.tsx",
      type: "registry:component",
      target: "components/beecharts/ui/dot.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/dot.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "dot"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bee-brush": {
    name: "bee-brush",
    description: "",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart"],
    files: [{
      path: "@/registry/ui/bee-brush.tsx",
      type: "registry:component",
      target: "components/beecharts/ui/bee-brush.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/bee-brush.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "bee-brush"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "background": {
    name: "background",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/ui/background.tsx",
      type: "registry:component",
      target: "components/beecharts/ui/background.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/background.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "background"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart": {
    name: "bar-chart",
    description: "Bar chart (ECharts engine, compound API)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/bar-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "line-chart": {
    name: "line-chart",
    description: "Line chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/line-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/line-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "composed-chart": {
    name: "composed-chart",
    description: "Composed bar + line chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/composed-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/composed-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "composed-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pie-chart": {
    name: "pie-chart",
    description: "Pie / donut chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/pie-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/pie-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "pie-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "heatmap-chart": {
    name: "heatmap-chart",
    description: "Heatmap chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/heatmap-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/heatmap-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/heatmap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "heatmap-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "calendar-chart": {
    name: "calendar-chart",
    description: "Calendar heatmap chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/calendar-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/calendar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/calendar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "calendar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radial-chart": {
    name: "radial-chart",
    description: "Radial / gauge chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/radial-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/radial-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "radial-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart": {
    name: "area-chart",
    description: "Area chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/area-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/area-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "area-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scatter-chart": {
    name: "scatter-chart",
    description: "Scatter / bubble chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/scatter-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/scatter-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/scatter-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "scatter-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radar-chart": {
    name: "radar-chart",
    description: "Radar chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/radar-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/radar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "radar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sankey-chart": {
    name: "sankey-chart",
    description: "Sankey flow chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/sankey-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/sankey-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "sankey-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart": {
    name: "funnel-chart",
    description: "Funnel chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/funnel-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/funnel-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/funnel-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "funnel-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waterfall-chart": {
    name: "waterfall-chart",
    description: "Waterfall chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/waterfall-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/waterfall-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/waterfall-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "waterfall-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "treemap-chart": {
    name: "treemap-chart",
    description: "Treemap chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/treemap-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/treemap-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/treemap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "treemap-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sparkline-chart": {
    name: "sparkline-chart",
    description: "Sparkline chart (ECharts engine)",
    type: "registry:component",
    registryDependencies: ["@beecharts/chart","@beecharts/tooltip","@beecharts/legend"],
    files: [{
      path: "@/registry/charts/sparkline-chart.tsx",
      type: "registry:component",
      target: "components/beecharts/charts/sparkline-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/charts/sparkline-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "sparkline-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chart-recipes": {
    name: "chart-recipes",
    description: "Data helpers for histogram, Pareto, heatmap, bullet, gauge, and box plot shapes",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "@/registry/lib/chart-recipes.ts",
      type: "registry:lib",
      target: "lib/chart-recipes.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/chart-recipes.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "chart-recipes"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bar-chart": {
    name: "ex-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-bar-chart": {
    name: "ex-loading-state-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-loading-state-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stacked-type-bar-chart": {
    name: "ex-stacked-type-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-stacked-type-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-stacked-type-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-stacked-type-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-percent-type-bar-chart": {
    name: "ex-percent-type-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-percent-type-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-percent-type-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-percent-type-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-horizontal-layout-bar-chart": {
    name: "ex-horizontal-layout-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-horizontal-layout-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-horizontal-layout-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-horizontal-layout-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hatched-variant-bar-chart": {
    name: "ex-hatched-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-hatched-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-hatched-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-hatched-variant-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stripped-variant-bar-chart": {
    name: "ex-stripped-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-stripped-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-stripped-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-stripped-variant-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-line-chart": {
    name: "ex-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-line-chart": {
    name: "ex-loading-state-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-loading-state-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-line-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-composed-chart": {
    name: "ex-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/composed-chart"],
    files: [{
      path: "@/registry/examples/ex-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-composed-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-composed-chart": {
    name: "ex-loading-state-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/composed-chart"],
    files: [{
      path: "@/registry/examples/ex-loading-state-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-composed-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-pareto-chart": {
    name: "ex-pareto-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/composed-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-pareto-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-pareto-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-pareto-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-pie-chart": {
    name: "ex-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/pie-chart"],
    files: [{
      path: "@/registry/examples/ex-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-pie-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gauge-chart": {
    name: "ex-gauge-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-gauge-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-gauge-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-gauge-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gauge-with-target-chart": {
    name: "ex-gauge-with-target-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-gauge-with-target-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-gauge-with-target-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-gauge-with-target-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-histogram-chart": {
    name: "ex-histogram-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-histogram-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-histogram-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-histogram-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-histogram-chart": {
    name: "ex-loading-state-histogram-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-loading-state-histogram-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-histogram-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-histogram-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bullet-chart": {
    name: "ex-bullet-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-bullet-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-bullet-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-bullet-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-pareto-chart": {
    name: "ex-loading-state-pareto-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/composed-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-loading-state-pareto-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-loading-state-pareto-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-loading-state-pareto-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-boxplot-chart": {
    name: "ex-boxplot-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/composed-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-boxplot-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-boxplot-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-boxplot-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-chart": {
    name: "ex-heatmap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/heatmap-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-weekly-chart": {
    name: "ex-heatmap-weekly-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/heatmap-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-weekly-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-weekly-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-weekly-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-correlation-chart": {
    name: "ex-heatmap-correlation-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/heatmap-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-correlation-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-correlation-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-correlation-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-workload-dashboard-chart": {
    name: "ex-workload-dashboard-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/calendar-chart","@beecharts/heatmap-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-workload-dashboard-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-workload-dashboard-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-workload-dashboard-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-calendar-workload-chart": {
    name: "ex-calendar-workload-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/calendar-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-calendar-workload-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-calendar-workload-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-calendar-workload-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-heatmap-team-workload-chart": {
    name: "ex-heatmap-team-workload-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/heatmap-chart","@beecharts/chart-recipes"],
    files: [{
      path: "@/registry/examples/ex-heatmap-team-workload-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-heatmap-team-workload-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "ex-heatmap-team-workload-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-dots-line-chart": {
    name: "ex-bg-dots-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgDotsLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgDotsLineChart"},
  },
  "ex-bg-graph-paper-line-chart": {
    name: "ex-bg-graph-paper-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgGraphPaperLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgGraphPaperLineChart"},
  },
  "ex-bg-cross-hatch-line-chart": {
    name: "ex-bg-cross-hatch-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgCrossHatchLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgCrossHatchLineChart"},
  },
  "ex-bg-diagonal-lines-line-chart": {
    name: "ex-bg-diagonal-lines-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgDiagonalLinesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgDiagonalLinesLineChart"},
  },
  "ex-bg-plus-line-chart": {
    name: "ex-bg-plus-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgPlusLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgPlusLineChart"},
  },
  "ex-bg-falling-triangles-line-chart": {
    name: "ex-bg-falling-triangles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgFallingTrianglesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgFallingTrianglesLineChart"},
  },
  "ex-bg-4-pointed-star-line-chart": {
    name: "ex-bg-4-pointed-star-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBg4PointedStarLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBg4PointedStarLineChart"},
  },
  "ex-bg-tiny-checkers-line-chart": {
    name: "ex-bg-tiny-checkers-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgTinyCheckersLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgTinyCheckersLineChart"},
  },
  "ex-bg-overlapping-circles-line-chart": {
    name: "ex-bg-overlapping-circles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgOverlappingCirclesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgOverlappingCirclesLineChart"},
  },
  "ex-bg-wiggle-lines-line-chart": {
    name: "ex-bg-wiggle-lines-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgWiggleLinesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgWiggleLinesLineChart"},
  },
  "ex-bg-bubbles-line-chart": {
    name: "ex-bg-bubbles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgBubblesLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgBubblesLineChart"},
  },
  "ex-legend-square-line-chart": {
    name: "ex-legend-square-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendSquareLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendSquareLineChart"},
  },
  "ex-legend-circle-line-chart": {
    name: "ex-legend-circle-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendCircleLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendCircleLineChart"},
  },
  "ex-legend-circle-outline-line-chart": {
    name: "ex-legend-circle-outline-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendCircleOutlineLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendCircleOutlineLineChart"},
  },
  "ex-legend-rounded-square-line-chart": {
    name: "ex-legend-rounded-square-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendRoundedSquareLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendRoundedSquareLineChart"},
  },
  "ex-legend-rounded-square-outline-line-chart": {
    name: "ex-legend-rounded-square-outline-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendRoundedSquareOutlineLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendRoundedSquareOutlineLineChart"},
  },
  "ex-legend-vertical-bar-line-chart": {
    name: "ex-legend-vertical-bar-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendVerticalBarLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendVerticalBarLineChart"},
  },
  "ex-legend-horizontal-bar-line-chart": {
    name: "ex-legend-horizontal-bar-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/line-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleLegendHorizontalBarLineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLegendHorizontalBarLineChart"},
  },
  "ex-tooltip-default-bar-chart": {
    name: "ex-tooltip-default-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleTooltipDefaultBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleTooltipDefaultBarChart"},
  },
  "ex-tooltip-frosted-glass-bar-chart": {
    name: "ex-tooltip-frosted-glass-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-ui-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-ui-charts.tsx")
      return { default: mod.default || mod["BeeExampleTooltipFrostedGlassBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleTooltipFrostedGlassBarChart"},
  },
  "ex-animated-dashed-stroke-area-chart": {
    name: "ex-animated-dashed-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleAnimatedDashedStrokeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleAnimatedDashedStrokeAreaChart"},
  },
  "ex-area-chart": {
    name: "ex-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleAreaChart"},
  },
  "ex-bg-bubbles-sparkline-chart": {
    name: "ex-bg-bubbles-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleBgBubblesSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBgBubblesSparklineChart"},
  },
  "ex-bubble-chart": {
    name: "ex-bubble-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleBubbleChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBubbleChart"},
  },
  "ex-bubble-sized-chart": {
    name: "ex-bubble-sized-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleBubbleSizedChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBubbleSizedChart"},
  },
  "ex-bump-curve-type-area-chart": {
    name: "ex-bump-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleBumpCurveTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleBumpCurveTypeAreaChart"},
  },
  "ex-chart-config-default-bar-chart": {
    name: "ex-chart-config-default-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleChartConfigDefaultBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleChartConfigDefaultBarChart"},
  },
  "ex-chart-config-icons-bar-chart": {
    name: "ex-chart-config-icons-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleChartConfigIconsBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleChartConfigIconsBarChart"},
  },
  "ex-circle-grid-radar-chart": {
    name: "ex-circle-grid-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleCircleGridRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleCircleGridRadarChart"},
  },
  "ex-dashed-stroke-area-chart": {
    name: "ex-dashed-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleDashedStrokeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleDashedStrokeAreaChart"},
  },
  "ex-default-type-area-chart": {
    name: "ex-default-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleDefaultTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleDefaultTypeAreaChart"},
  },
  "ex-dotted-area-variant-area-chart": {
    name: "ex-dotted-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleDottedAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleDottedAreaVariantAreaChart"},
  },
  "ex-expanded-type-area-chart": {
    name: "ex-expanded-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleExpandedTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleExpandedTypeAreaChart"},
  },
  "ex-funnel-chart": {
    name: "ex-funnel-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/funnel-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleFunnelChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleFunnelChart"},
  },
  "ex-glowing-bubble-chart": {
    name: "ex-glowing-bubble-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingBubbleChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingBubbleChart"},
  },
  "ex-glowing-funnel-chart": {
    name: "ex-glowing-funnel-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/funnel-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingFunnelChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingFunnelChart"},
  },
  "ex-glowing-radar-chart": {
    name: "ex-glowing-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingRadarChart"},
  },
  "ex-glowing-radial-chart": {
    name: "ex-glowing-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingRadialChart"},
  },
  "ex-glowing-sankey-chart": {
    name: "ex-glowing-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingSankeyChart"},
  },
  "ex-glowing-scatter-chart": {
    name: "ex-glowing-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingScatterChart"},
  },
  "ex-glowing-sparkline-chart": {
    name: "ex-glowing-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingSparklineChart"},
  },
  "ex-glowing-treemap-chart": {
    name: "ex-glowing-treemap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/treemap-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingTreemapChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingTreemapChart"},
  },
  "ex-glowing-waterfall-chart": {
    name: "ex-glowing-waterfall-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/waterfall-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGlowingWaterfallChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGlowingWaterfallChart"},
  },
  "ex-gradient-area-variant-area-chart": {
    name: "ex-gradient-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientAreaVariantAreaChart"},
  },
  "ex-gradient-colors-area-chart": {
    name: "ex-gradient-colors-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsAreaChart"},
  },
  "ex-gradient-colors-bar-chart": {
    name: "ex-gradient-colors-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsBarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsBarChart"},
  },
  "ex-gradient-colors-bump-area-chart": {
    name: "ex-gradient-colors-bump-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsBumpAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsBumpAreaChart"},
  },
  "ex-gradient-colors-radar-chart": {
    name: "ex-gradient-colors-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsRadarChart"},
  },
  "ex-gradient-colors-radial-chart": {
    name: "ex-gradient-colors-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsRadialChart"},
  },
  "ex-gradient-colors-sankey-chart": {
    name: "ex-gradient-colors-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsSankeyChart"},
  },
  "ex-gradient-colors-scatter-chart": {
    name: "ex-gradient-colors-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientColorsScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientColorsScatterChart"},
  },
  "ex-gradient-reverse-area-variant-area-chart": {
    name: "ex-gradient-reverse-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleGradientReverseAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleGradientReverseAreaVariantAreaChart"},
  },
  "ex-hatched-area-variant-area-chart": {
    name: "ex-hatched-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleHatchedAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleHatchedAreaVariantAreaChart"},
  },
  "ex-labeled-nodes-sankey-chart": {
    name: "ex-labeled-nodes-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLabeledNodesSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLabeledNodesSankeyChart"},
  },
  "ex-lines-area-variant-area-chart": {
    name: "ex-lines-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLinesAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLinesAreaVariantAreaChart"},
  },
  "ex-lines-variant-radar-chart": {
    name: "ex-lines-variant-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLinesVariantRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLinesVariantRadarChart"},
  },
  "ex-loading-state-area-chart": {
    name: "ex-loading-state-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateAreaChart"},
  },
  "ex-loading-state-bubble-chart": {
    name: "ex-loading-state-bubble-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateBubbleChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateBubbleChart"},
  },
  "ex-loading-state-funnel-chart": {
    name: "ex-loading-state-funnel-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/funnel-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateFunnelChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateFunnelChart"},
  },
  "ex-loading-state-gauge-chart": {
    name: "ex-loading-state-gauge-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateGaugeChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateGaugeChart"},
  },
  "ex-loading-state-radar-chart": {
    name: "ex-loading-state-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateRadarChart"},
  },
  "ex-loading-state-radial-chart": {
    name: "ex-loading-state-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateRadialChart"},
  },
  "ex-loading-state-sankey-chart": {
    name: "ex-loading-state-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateSankeyChart"},
  },
  "ex-loading-state-scatter-chart": {
    name: "ex-loading-state-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateScatterChart"},
  },
  "ex-loading-state-sparkline-chart": {
    name: "ex-loading-state-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateSparklineChart"},
  },
  "ex-loading-state-treemap-chart": {
    name: "ex-loading-state-treemap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/treemap-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateTreemapChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateTreemapChart"},
  },
  "ex-loading-state-waterfall-chart": {
    name: "ex-loading-state-waterfall-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/waterfall-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleLoadingStateWaterfallChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleLoadingStateWaterfallChart"},
  },
  "ex-monotoney-curve-type-area-chart": {
    name: "ex-monotoney-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleMonotoneyCurveTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleMonotoneyCurveTypeAreaChart"},
  },
  "ex-outside-labels-sankey-chart": {
    name: "ex-outside-labels-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleOutsideLabelsSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleOutsideLabelsSankeyChart"},
  },
  "ex-radar-chart": {
    name: "ex-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radar-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleRadarChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleRadarChart"},
  },
  "ex-radial-chart": {
    name: "ex-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleRadialChart"},
  },
  "ex-sankey-chart": {
    name: "ex-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSankeyChart"},
  },
  "ex-scatter-chart": {
    name: "ex-scatter-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/scatter-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleScatterChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleScatterChart"},
  },
  "ex-semi-variant-radial-chart": {
    name: "ex-semi-variant-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSemiVariantRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSemiVariantRadialChart"},
  },
  "ex-rose-radial-chart": {
    name: "ex-rose-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/radial-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleRoseRadialChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleRoseRadialChart"},
  },
  "ex-solid-area-variant-area-chart": {
    name: "ex-solid-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSolidAreaVariantAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSolidAreaVariantAreaChart"},
  },
  "ex-solid-labeled-nodes-sankey-chart": {
    name: "ex-solid-labeled-nodes-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSolidLabeledNodesSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSolidLabeledNodesSankeyChart"},
  },
  "ex-solid-link-variant-sankey-chart": {
    name: "ex-solid-link-variant-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSolidLinkVariantSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSolidLinkVariantSankeyChart"},
  },
  "ex-solid-stroke-area-chart": {
    name: "ex-solid-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSolidStrokeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSolidStrokeAreaChart"},
  },
  "ex-source-link-variant-sankey-chart": {
    name: "ex-source-link-variant-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sankey-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSourceLinkVariantSankeyChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSourceLinkVariantSankeyChart"},
  },
  "ex-sparkline-area-chart": {
    name: "ex-sparkline-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSparklineAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSparklineAreaChart"},
  },
  "ex-sparkline-chart": {
    name: "ex-sparkline-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSparklineChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSparklineChart"},
  },
  "ex-stacked-type-area-chart": {
    name: "ex-stacked-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleStackedTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleStackedTypeAreaChart"},
  },
  "ex-step-curve-type-area-chart": {
    name: "ex-step-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/area-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleStepCurveTypeAreaChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleStepCurveTypeAreaChart"},
  },
  "ex-treemap-chart": {
    name: "ex-treemap-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/treemap-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleTreemapChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleTreemapChart"},
  },
  "ex-waterfall-chart": {
    name: "ex-waterfall-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/waterfall-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleWaterfallChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleWaterfallChart"},
  },
  "ex-sparkline-end-dot-chart": {
    name: "ex-sparkline-end-dot-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSparklineEndDotChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSparklineEndDotChart"},
  },
  "ex-sparkline-reference-band-chart": {
    name: "ex-sparkline-reference-band-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@beecharts/sparkline-chart"],
    files: [{
      path: "@/registry/examples/ex-doc-charts.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/ex-doc-charts.tsx")
      return { default: mod.default || mod["BeeExampleSparklineReferenceBandChart"] }
    }),
    categories: undefined,
    meta: {"exportName":"BeeExampleSparklineReferenceBandChart"},
  },
  "monospace-bar-chart": {
    name: "monospace-bar-chart",
    description: "Terminal-style bar chart with monospace KPI chrome (ECharts)",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-monospace-bar-chart.tsx",
      type: "registry:block",
      target: "components/beecharts/blocks/monospace-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-monospace-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "monospace-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "hover-trace-bar-chart": {
    name: "hover-trace-bar-chart",
    description: "Bar chart with KPI header trace (ECharts)",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-hover-trace-bar-chart.tsx",
      type: "registry:block",
      target: "components/beecharts/blocks/hover-trace-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-hover-trace-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "hover-trace-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-bar-chart": {
    name: "grid-bar-chart",
    description: "Stacked ghost grid bar chart (ECharts)",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-grid-bar-chart.tsx",
      type: "registry:block",
      target: "components/beecharts/blocks/grid-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-grid-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "grid-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "isometric-bar-chart": {
    name: "isometric-bar-chart",
    description: "Rounded bar chart block (ECharts)",
    type: "registry:block",
    registryDependencies: ["@beecharts/bar-chart"],
    files: [{
      path: "@/registry/blocks/b-isometric-bar-chart.tsx",
      type: "registry:block",
      target: "components/beecharts/blocks/isometric-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/b-isometric-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function') || "isometric-bar-chart"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }