import type { Registry } from "shadcn/schema";

const FILE = "examples/ex-doc-charts.tsx";

function ex(name: string, exportName: string, deps: string[]) {
  return { name, registryDependencies: deps, type: "registry:block" as const, files: [{ path: FILE, type: "registry:block" as const }], meta: { exportName } };
}

export const docExamples: Registry["items"] = [
  ex("ex-animated-dashed-stroke-area-chart", "BeeExampleAnimatedDashedStrokeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-area-chart", "BeeExampleAreaChart", ["@beecharts/area-chart"]),
  ex("ex-bg-bubbles-sparkline-chart", "BeeExampleBgBubblesSparklineChart", ["@beecharts/sparkline-chart"]),
  ex("ex-bubble-chart", "BeeExampleBubbleChart", ["@beecharts/scatter-chart"]),
  ex("ex-bubble-sized-chart", "BeeExampleBubbleSizedChart", ["@beecharts/scatter-chart"]),
  ex("ex-bump-curve-type-area-chart", "BeeExampleBumpCurveTypeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-chart-config-default-bar-chart", "BeeExampleChartConfigDefaultBarChart", ["@beecharts/bar-chart"]),
  ex("ex-chart-config-icons-bar-chart", "BeeExampleChartConfigIconsBarChart", ["@beecharts/bar-chart"]),
  ex("ex-circle-grid-radar-chart", "BeeExampleCircleGridRadarChart", ["@beecharts/radar-chart"]),
  ex("ex-dashed-stroke-area-chart", "BeeExampleDashedStrokeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-default-type-area-chart", "BeeExampleDefaultTypeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-dotted-area-variant-area-chart", "BeeExampleDottedAreaVariantAreaChart", ["@beecharts/area-chart"]),
  ex("ex-expanded-type-area-chart", "BeeExampleExpandedTypeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-funnel-chart", "BeeExampleFunnelChart", ["@beecharts/funnel-chart"]),
  ex("ex-glowing-bubble-chart", "BeeExampleGlowingBubbleChart", ["@beecharts/scatter-chart"]),
  ex("ex-glowing-funnel-chart", "BeeExampleGlowingFunnelChart", ["@beecharts/funnel-chart"]),
  ex("ex-glowing-radar-chart", "BeeExampleGlowingRadarChart", ["@beecharts/radar-chart"]),
  ex("ex-glowing-radial-chart", "BeeExampleGlowingRadialChart", ["@beecharts/radial-chart"]),
  ex("ex-glowing-sankey-chart", "BeeExampleGlowingSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-glowing-scatter-chart", "BeeExampleGlowingScatterChart", ["@beecharts/scatter-chart"]),
  ex("ex-glowing-sparkline-chart", "BeeExampleGlowingSparklineChart", ["@beecharts/sparkline-chart"]),
  ex("ex-glowing-treemap-chart", "BeeExampleGlowingTreemapChart", ["@beecharts/treemap-chart"]),
  ex("ex-glowing-waterfall-chart", "BeeExampleGlowingWaterfallChart", ["@beecharts/waterfall-chart"]),
  ex("ex-gradient-area-variant-area-chart", "BeeExampleGradientAreaVariantAreaChart", ["@beecharts/area-chart"]),
  ex("ex-gradient-colors-area-chart", "BeeExampleGradientColorsAreaChart", ["@beecharts/area-chart"]),
  ex("ex-gradient-colors-bar-chart", "BeeExampleGradientColorsBarChart", ["@beecharts/bar-chart"]),
  ex("ex-gradient-colors-bump-area-chart", "BeeExampleGradientColorsBumpAreaChart", ["@beecharts/area-chart"]),
  ex("ex-gradient-colors-radar-chart", "BeeExampleGradientColorsRadarChart", ["@beecharts/radar-chart"]),
  ex("ex-gradient-colors-radial-chart", "BeeExampleGradientColorsRadialChart", ["@beecharts/radial-chart"]),
  ex("ex-gradient-colors-sankey-chart", "BeeExampleGradientColorsSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-gradient-colors-scatter-chart", "BeeExampleGradientColorsScatterChart", ["@beecharts/scatter-chart"]),
  ex("ex-gradient-reverse-area-variant-area-chart", "BeeExampleGradientReverseAreaVariantAreaChart", ["@beecharts/area-chart"]),
  ex("ex-hatched-area-variant-area-chart", "BeeExampleHatchedAreaVariantAreaChart", ["@beecharts/area-chart"]),
  ex("ex-labeled-nodes-sankey-chart", "BeeExampleLabeledNodesSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-lines-area-variant-area-chart", "BeeExampleLinesAreaVariantAreaChart", ["@beecharts/area-chart"]),
  ex("ex-lines-variant-radar-chart", "BeeExampleLinesVariantRadarChart", ["@beecharts/radar-chart"]),
  ex("ex-loading-state-area-chart", "BeeExampleLoadingStateAreaChart", ["@beecharts/area-chart"]),
  ex("ex-loading-state-bubble-chart", "BeeExampleLoadingStateBubbleChart", ["@beecharts/scatter-chart"]),
  ex("ex-loading-state-funnel-chart", "BeeExampleLoadingStateFunnelChart", ["@beecharts/funnel-chart"]),
  ex("ex-loading-state-gauge-chart", "BeeExampleLoadingStateGaugeChart", ["@beecharts/radial-chart"]),
  ex("ex-loading-state-radar-chart", "BeeExampleLoadingStateRadarChart", ["@beecharts/radar-chart"]),
  ex("ex-loading-state-radial-chart", "BeeExampleLoadingStateRadialChart", ["@beecharts/radial-chart"]),
  ex("ex-loading-state-sankey-chart", "BeeExampleLoadingStateSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-loading-state-scatter-chart", "BeeExampleLoadingStateScatterChart", ["@beecharts/scatter-chart"]),
  ex("ex-loading-state-sparkline-chart", "BeeExampleLoadingStateSparklineChart", ["@beecharts/sparkline-chart"]),
  ex("ex-loading-state-treemap-chart", "BeeExampleLoadingStateTreemapChart", ["@beecharts/treemap-chart"]),
  ex("ex-loading-state-waterfall-chart", "BeeExampleLoadingStateWaterfallChart", ["@beecharts/waterfall-chart"]),
  ex("ex-monotoney-curve-type-area-chart", "BeeExampleMonotoneyCurveTypeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-outside-labels-sankey-chart", "BeeExampleOutsideLabelsSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-radar-chart", "BeeExampleRadarChart", ["@beecharts/radar-chart"]),
  ex("ex-radial-chart", "BeeExampleRadialChart", ["@beecharts/radial-chart"]),
  ex("ex-sankey-chart", "BeeExampleSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-scatter-chart", "BeeExampleScatterChart", ["@beecharts/scatter-chart"]),
  ex("ex-semi-variant-radial-chart", "BeeExampleSemiVariantRadialChart", ["@beecharts/radial-chart"]),
  ex("ex-rose-radial-chart", "BeeExampleRoseRadialChart", ["@beecharts/radial-chart"]),
  ex("ex-solid-area-variant-area-chart", "BeeExampleSolidAreaVariantAreaChart", ["@beecharts/area-chart"]),
  ex("ex-solid-labeled-nodes-sankey-chart", "BeeExampleSolidLabeledNodesSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-solid-link-variant-sankey-chart", "BeeExampleSolidLinkVariantSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-solid-stroke-area-chart", "BeeExampleSolidStrokeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-source-link-variant-sankey-chart", "BeeExampleSourceLinkVariantSankeyChart", ["@beecharts/sankey-chart"]),
  ex("ex-sparkline-area-chart", "BeeExampleSparklineAreaChart", ["@beecharts/sparkline-chart"]),
  ex("ex-sparkline-chart", "BeeExampleSparklineChart", ["@beecharts/sparkline-chart"]),
  ex("ex-stacked-type-area-chart", "BeeExampleStackedTypeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-step-curve-type-area-chart", "BeeExampleStepCurveTypeAreaChart", ["@beecharts/area-chart"]),
  ex("ex-treemap-chart", "BeeExampleTreemapChart", ["@beecharts/treemap-chart"]),
  ex("ex-waterfall-chart", "BeeExampleWaterfallChart", ["@beecharts/waterfall-chart"]),
  ex("ex-sparkline-end-dot-chart", "BeeExampleSparklineEndDotChart", ["@beecharts/sparkline-chart"]),
  ex(
    "ex-sparkline-reference-band-chart",
    "BeeExampleSparklineReferenceBandChart",
    ["@beecharts/sparkline-chart"],
  ),
];
