import type { Registry } from "shadcn/schema";

const FILE = "examples/ex-doc-charts.tsx";

function ex(name: string, exportName: string, deps: string[]) {
  return { name, registryDependencies: deps, type: "registry:block" as const, files: [{ path: FILE, type: "registry:block" as const }], meta: { exportName } };
}

export const docExamples: Registry["items"] = [
  ex("ex-animated-dashed-stroke-area-chart", "NQExampleAnimatedDashedStrokeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-area-chart", "NQExampleAreaChart", ["@nqchart/area-chart"]),
  ex("ex-bg-bubbles-sparkline-chart", "NQExampleBgBubblesSparklineChart", ["@nqchart/sparkline-chart"]),
  ex("ex-bubble-chart", "NQExampleBubbleChart", ["@nqchart/scatter-chart"]),
  ex("ex-bubble-sized-chart", "NQExampleBubbleSizedChart", ["@nqchart/scatter-chart"]),
  ex("ex-bump-curve-type-area-chart", "NQExampleBumpCurveTypeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-chart-config-default-bar-chart", "NQExampleChartConfigDefaultBarChart", ["@nqchart/bar-chart"]),
  ex("ex-chart-config-icons-bar-chart", "NQExampleChartConfigIconsBarChart", ["@nqchart/bar-chart"]),
  ex("ex-circle-grid-radar-chart", "NQExampleCircleGridRadarChart", ["@nqchart/radar-chart"]),
  ex("ex-dashed-stroke-area-chart", "NQExampleDashedStrokeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-default-type-area-chart", "NQExampleDefaultTypeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-dotted-area-variant-area-chart", "NQExampleDottedAreaVariantAreaChart", ["@nqchart/area-chart"]),
  ex("ex-expanded-type-area-chart", "NQExampleExpandedTypeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-funnel-chart", "NQExampleFunnelChart", ["@nqchart/funnel-chart"]),
  ex("ex-glowing-bubble-chart", "NQExampleGlowingBubbleChart", ["@nqchart/scatter-chart"]),
  ex("ex-glowing-funnel-chart", "NQExampleGlowingFunnelChart", ["@nqchart/funnel-chart"]),
  ex("ex-glowing-radar-chart", "NQExampleGlowingRadarChart", ["@nqchart/radar-chart"]),
  ex("ex-glowing-radial-chart", "NQExampleGlowingRadialChart", ["@nqchart/radial-chart"]),
  ex("ex-glowing-scatter-chart", "NQExampleGlowingScatterChart", ["@nqchart/scatter-chart"]),
  ex("ex-glowing-sparkline-chart", "NQExampleGlowingSparklineChart", ["@nqchart/sparkline-chart"]),
  ex("ex-glowing-treemap-chart", "NQExampleGlowingTreemapChart", ["@nqchart/treemap-chart"]),
  ex("ex-glowing-waterfall-chart", "NQExampleGlowingWaterfallChart", ["@nqchart/waterfall-chart"]),
  ex("ex-gradient-area-variant-area-chart", "NQExampleGradientAreaVariantAreaChart", ["@nqchart/area-chart"]),
  ex("ex-gradient-colors-area-chart", "NQExampleGradientColorsAreaChart", ["@nqchart/area-chart"]),
  ex("ex-gradient-colors-bar-chart", "NQExampleGradientColorsBarChart", ["@nqchart/bar-chart"]),
  ex("ex-gradient-colors-bump-area-chart", "NQExampleGradientColorsBumpAreaChart", ["@nqchart/area-chart"]),
  ex("ex-gradient-colors-radar-chart", "NQExampleGradientColorsRadarChart", ["@nqchart/radar-chart"]),
  ex("ex-gradient-colors-radial-chart", "NQExampleGradientColorsRadialChart", ["@nqchart/radial-chart"]),
  ex("ex-gradient-colors-scatter-chart", "NQExampleGradientColorsScatterChart", ["@nqchart/scatter-chart"]),
  ex("ex-gradient-reverse-area-variant-area-chart", "NQExampleGradientReverseAreaVariantAreaChart", ["@nqchart/area-chart"]),
  ex("ex-hatched-area-variant-area-chart", "NQExampleHatchedAreaVariantAreaChart", ["@nqchart/area-chart"]),
  ex("ex-lines-area-variant-area-chart", "NQExampleLinesAreaVariantAreaChart", ["@nqchart/area-chart"]),
  ex("ex-lines-variant-radar-chart", "NQExampleLinesVariantRadarChart", ["@nqchart/radar-chart"]),
  ex("ex-loading-state-area-chart", "NQExampleLoadingStateAreaChart", ["@nqchart/area-chart"]),
  ex("ex-loading-state-bubble-chart", "NQExampleLoadingStateBubbleChart", ["@nqchart/scatter-chart"]),
  ex("ex-loading-state-funnel-chart", "NQExampleLoadingStateFunnelChart", ["@nqchart/funnel-chart"]),
  ex("ex-loading-state-gauge-chart", "NQExampleLoadingStateGaugeChart", ["@nqchart/radial-chart"]),
  ex("ex-loading-state-radar-chart", "NQExampleLoadingStateRadarChart", ["@nqchart/radar-chart"]),
  ex("ex-loading-state-radial-chart", "NQExampleLoadingStateRadialChart", ["@nqchart/radial-chart"]),
  ex("ex-loading-state-scatter-chart", "NQExampleLoadingStateScatterChart", ["@nqchart/scatter-chart"]),
  ex("ex-loading-state-sparkline-chart", "NQExampleLoadingStateSparklineChart", ["@nqchart/sparkline-chart"]),
  ex("ex-loading-state-treemap-chart", "NQExampleLoadingStateTreemapChart", ["@nqchart/treemap-chart"]),
  ex("ex-loading-state-waterfall-chart", "NQExampleLoadingStateWaterfallChart", ["@nqchart/waterfall-chart"]),
  ex("ex-monotoney-curve-type-area-chart", "NQExampleMonotoneyCurveTypeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-radar-chart", "NQExampleRadarChart", ["@nqchart/radar-chart"]),
  ex("ex-radial-chart", "NQExampleRadialChart", ["@nqchart/radial-chart"]),
  ex("ex-scatter-chart", "NQExampleScatterChart", ["@nqchart/scatter-chart"]),
  ex("ex-semi-variant-radial-chart", "NQExampleSemiVariantRadialChart", ["@nqchart/radial-chart"]),
  ex("ex-rose-radial-chart", "NQExampleRoseRadialChart", ["@nqchart/radial-chart"]),
  ex("ex-solid-area-variant-area-chart", "NQExampleSolidAreaVariantAreaChart", ["@nqchart/area-chart"]),
  ex("ex-solid-stroke-area-chart", "NQExampleSolidStrokeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-sparkline-area-chart", "NQExampleSparklineAreaChart", ["@nqchart/sparkline-chart"]),
  ex("ex-sparkline-chart", "NQExampleSparklineChart", ["@nqchart/sparkline-chart"]),
  ex("ex-stacked-type-area-chart", "NQExampleStackedTypeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-step-curve-type-area-chart", "NQExampleStepCurveTypeAreaChart", ["@nqchart/area-chart"]),
  ex("ex-treemap-chart", "NQExampleTreemapChart", ["@nqchart/treemap-chart"]),
  ex("ex-waterfall-chart", "NQExampleWaterfallChart", ["@nqchart/waterfall-chart"]),
  ex("ex-sparkline-end-dot-chart", "NQExampleSparklineEndDotChart", ["@nqchart/sparkline-chart"]),
  ex(
    "ex-sparkline-reference-band-chart",
    "NQExampleSparklineReferenceBandChart",
    ["@nqchart/sparkline-chart"],
  ),
];
