#!/usr/bin/env node
/**
 * Consumer-payload gate: bundle each family entry with esbuild (echarts
 * included, react/motion external), gzip, compare to scripts/size-baseline.json.
 *
 * Fails when any entry grows more than THRESHOLD over its committed baseline.
 * Write a new baseline with: node scripts/check-size.mjs --write
 *
 * Requires nothing in dist/ — measures source the way a consumer bundler would.
 */
import { gzipSync } from "node:zlib";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const baselinePath = join(root, "scripts", "size-baseline.json");
const outDir = join(root, ".size-probe");
const THRESHOLD = 0.05;
const writeBaseline = process.argv.includes("--write");

const FAMILIES = [
  "area-chart",
  "bar-chart",
  "calendar-chart",
  "composed-chart",
  "funnel-chart",
  "heatmap-chart",
  "line-chart",
  "pie-chart",
  "radar-chart",
  "radial-chart",
  "scatter-chart",
  "sparkline-chart",
  "treemap-chart",
  "waterfall-chart",
];

function kb(bytes) {
  return Math.round((bytes / 1024) * 10) / 10;
}

async function measureFamily(family) {
  const entry = join(root, "src", "registry", "charts", `${family}.tsx`);
  const outfile = join(outDir, `${family}.mjs`);
  const result = await esbuild.build({
    absWorkingDir: root,
    entryPoints: [entry],
    bundle: true,
    minify: true,
    format: "esm",
    platform: "browser",
    target: "es2020",
    outfile,
    write: true,
    logLevel: "silent",
    alias: { "@": join(root, "src") },
    external: [
      "react",
      "react-dom",
      "react/jsx-runtime",
      "motion",
      "motion/react",
    ],
    loader: { ".css": "empty" },
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
    },
  });
  if (result.errors.length) {
    throw new Error(
      `check:size — esbuild failed for ${family}:\n${result.errors.map((e) => e.text).join("\n")}`,
    );
  }
  const minified = readFileSync(outfile);
  const gzip = gzipSync(minified, { level: 9 });
  return { minified: minified.length, gzip: gzip.length };
}

mkdirSync(outDir, { recursive: true });

const sizes = {};
for (const family of FAMILIES) {
  sizes[family] = await measureFamily(family);
}

rmSync(outDir, { recursive: true, force: true });

const rows = FAMILIES.map((family) => {
  const s = sizes[family];
  return `  ${family.padEnd(18)} ${String(kb(s.minified)).padStart(7)} KB min   ${String(kb(s.gzip)).padStart(6)} KB gzip`;
});
console.info(`check:size — measured (threshold ${(THRESHOLD * 100).toFixed(0)}%):\n${rows.join("\n")}`);

if (writeBaseline) {
  const payload = {
    threshold: THRESHOLD,
    note: "esbuild minify + gzip; echarts included; react/motion external. Regenerated by `node scripts/check-size.mjs --write`.",
    sizes,
  };
  writeFileSync(baselinePath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  console.info(`check:size — wrote ${baselinePath}`);
  process.exit(0);
}

if (!existsSync(baselinePath)) {
  console.error(
    "check:size — missing scripts/size-baseline.json. Run `node scripts/check-size.mjs --write` after a deliberate payload change.",
  );
  process.exit(1);
}

const baseline = JSON.parse(readFileSync(baselinePath, "utf8"));
const failures = [];
for (const family of FAMILIES) {
  const current = sizes[family]?.gzip;
  const prev = baseline.sizes?.[family]?.gzip;
  if (typeof prev !== "number") {
    failures.push(`${family}: no baseline gzip (add via --write)`);
    continue;
  }
  const limit = Math.ceil(prev * (1 + (baseline.threshold ?? THRESHOLD)));
  if (current > limit) {
    failures.push(
      `${family}: ${kb(current)} KB gzip > ${kb(limit)} KB (${kb(prev)} KB baseline + ${((baseline.threshold ?? THRESHOLD) * 100).toFixed(0)}%)`,
    );
  }
}

if (failures.length) {
  console.error(`check:size — payload grew past threshold:\n  ${failures.join("\n  ")}`);
  process.exit(1);
}

console.info("check:size — ok (no family grew more than 5% over baseline)");
